<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="instance-1" failures="1" tests="2" name="Test" time="0.049" errors="0" timestamp="04 Jun 2022 13:42:00 GMT">
  <testcase classname="com.TestNg.learn.Surefile_testng" name="passingTest" time="0.015"/>
  <testcase classname="com.TestNg.learn.Surefile_testng" name="testingSurefire" time="0.003">
    <failure type="java.lang.AssertionError" message="This is the 2nd failed test">
      <![CDATA[java.lang.AssertionError: This is the 2nd failed test
at com.TestNg.learn.Surefile_testng.testingSurefire(Surefile_testng.java:16)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testingSurefire -->
</testsuite> <!-- Test -->
